/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsNumbersRouteImport } from './routes/_app/settings/numbers'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNumbersRoute = AppSettingsNumbersRouteImport.update({
  id: '/settings/numbers',
  path: '/settings/numbers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/settings/numbers': typeof AppSettingsNumbersRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/': typeof AppIndexRoute
  '/settings/numbers': typeof AppSettingsNumbersRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/numbers': typeof AppSettingsNumbersRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contacts'
    | '/inbox'
    | '/settings/numbers'
    | '/settings/team'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contacts'
    | '/inbox'
    | '/'
    | '/settings/numbers'
    | '/settings/team'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/contacts'
    | '/_app/inbox'
    | '/_app/'
    | '/_app/settings/numbers'
    | '/_app/settings/team'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/numbers': {
      id: '/_app/settings/numbers'
      path: '/settings/numbers'
      fullPath: '/settings/numbers'
      preLoaderRoute: typeof AppSettingsNumbersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppContactsRoute: typeof AppContactsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsNumbersRoute: typeof AppSettingsNumbersRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppContactsRoute: AppContactsRoute,
  AppInboxRoute: AppInboxRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsNumbersRoute: AppSettingsNumbersRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
