/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SelectOrgRouteImport } from './routes/select-org'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppBroadcastRouteImport } from './routes/_app/broadcast'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppTemplatesRouteImport } from './routes/_app/templates'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsConfigRouteImport } from './routes/_app/settings/config'
import { Route as AppSettingsNumbersRouteImport } from './routes/_app/settings/numbers'
import { Route as AppSettingsOrgRouteImport } from './routes/_app/settings/org'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrgRoute = SelectOrgRouteImport.update({
  id: '/select-org',
  path: '/select-org',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBroadcastRoute = AppBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsConfigRoute = AppSettingsConfigRouteImport.update({
  id: '/settings/config',
  path: '/settings/config',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNumbersRoute = AppSettingsNumbersRouteImport.update({
  id: '/settings/numbers',
  path: '/settings/numbers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsOrgRoute = AppSettingsOrgRouteImport.update({
  id: '/settings/org',
  path: '/settings/org',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AccountRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/analytics': typeof AppAnalyticsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/templates': typeof AppTemplatesRoute
  '/settings/config': typeof AppSettingsConfigRoute
  '/settings/numbers': typeof AppSettingsNumbersRoute
  '/settings/org': typeof AppSettingsOrgRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/account': typeof AccountRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/analytics': typeof AppAnalyticsRoute
  '/broadcast': typeof AppBroadcastRoute
  '/contacts': typeof AppContactsRoute
  '/inbox': typeof AppInboxRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/settings/config': typeof AppSettingsConfigRoute
  '/settings/numbers': typeof AppSettingsNumbersRoute
  '/settings/org': typeof AppSettingsOrgRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/account': typeof AccountRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/select-org': typeof SelectOrgRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/broadcast': typeof AppBroadcastRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/settings/config': typeof AppSettingsConfigRoute
  '/_app/settings/numbers': typeof AppSettingsNumbersRoute
  '/_app/settings/org': typeof AppSettingsOrgRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/join'
    | '/login'
    | '/select-org'
    | '/analytics'
    | '/broadcast'
    | '/contacts'
    | '/inbox'
    | '/templates'
    | '/settings/config'
    | '/settings/numbers'
    | '/settings/org'
    | '/settings/team'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/join'
    | '/login'
    | '/select-org'
    | '/analytics'
    | '/broadcast'
    | '/contacts'
    | '/inbox'
    | '/templates'
    | '/'
    | '/settings/config'
    | '/settings/numbers'
    | '/settings/org'
    | '/settings/team'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/account'
    | '/join'
    | '/login'
    | '/select-org'
    | '/_app/analytics'
    | '/_app/broadcast'
    | '/_app/contacts'
    | '/_app/inbox'
    | '/_app/templates'
    | '/_app/'
    | '/_app/settings/config'
    | '/_app/settings/numbers'
    | '/_app/settings/org'
    | '/_app/settings/team'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AccountRoute: typeof AccountRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  SelectOrgRoute: typeof SelectOrgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-org': {
      id: '/select-org'
      path: '/select-org'
      fullPath: '/select-org'
      preLoaderRoute: typeof SelectOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/broadcast': {
      id: '/_app/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof AppBroadcastRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/config': {
      id: '/_app/settings/config'
      path: '/settings/config'
      fullPath: '/settings/config'
      preLoaderRoute: typeof AppSettingsConfigRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/numbers': {
      id: '/_app/settings/numbers'
      path: '/settings/numbers'
      fullPath: '/settings/numbers'
      preLoaderRoute: typeof AppSettingsNumbersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/org': {
      id: '/_app/settings/org'
      path: '/settings/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof AppSettingsOrgRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBroadcastRoute: typeof AppBroadcastRoute
  AppContactsRoute: typeof AppContactsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsConfigRoute: typeof AppSettingsConfigRoute
  AppSettingsNumbersRoute: typeof AppSettingsNumbersRoute
  AppSettingsOrgRoute: typeof AppSettingsOrgRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBroadcastRoute: AppBroadcastRoute,
  AppContactsRoute: AppContactsRoute,
  AppInboxRoute: AppInboxRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsConfigRoute: AppSettingsConfigRoute,
  AppSettingsNumbersRoute: AppSettingsNumbersRoute,
  AppSettingsOrgRoute: AppSettingsOrgRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AccountRoute: AccountRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  SelectOrgRoute: SelectOrgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
