name: Build Wago

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating System
        required: true
        type: choice
        options:
          - darwin
          - linux
          - windows
      arch:
        description: CPU Architecture
        required: true
        type: choice
        options:
          - arm64
          - amd64

permissions:
  contents: read # Grants permission to create GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Nub
        uses: nubjs/setup-nub@v0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Setup deps
        run: nub run setup && nub run build:frontend

      - name: Generate filename
        id: filename
        run: echo "FILEPATH=./tmp/wago-${{ inputs.os }}-${{ inputs.arch }}${{ inputs.os == 'windows' && '.exe' || '' }}"  >> "$GITHUB_OUTPUT"

      - name: Build server
        run: go build -trimpath -o ${{ steps.filename.outputs.FILEPATH }} .
        env:
          CGO_ENABLED: 0
          GOOS: ${{ inputs.os }}
          GOARCH: ${{ inputs.arch }}

      - name: Upload binary
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.filename.outputs.FILEPATH }}
          retention-days: 7
          if-no-files-found: error
          overwrite: true
          archive: false
