name: Sanity check

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read # Grants permission to create GitHub Releases

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Nub
        uses: nubjs/setup-nub@v0

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"

      - name: Setup deps
        run: nub run setup

      - name: Lint
        run: nub run lint:frontend

      - name: Build server
        run: nub run build
