name: Sanity check

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read # Grants permission to create GitHub Releases

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js/NUB (for React frontend)
        uses: nubjs/setup-nub@v0
        with:
          working-directory: ./frontend/

      - name: Setup frontend
        working-directory: ./frontend
        run: nub install

      - name: Build frontend
        working-directory: ./frontend
        run: nub run lint; nub run build

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup server
        run: go mod tidy

      - name: Build server
        run: go build -gcflags='all=-N -l' .

      - name: Upload Go test results
        uses: actions/upload-artifact@v7
        with:
          name: wago-ubuntu
          path: wago
